name: PR Check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x64]
        include:
          - arch: x64
            platform: win-x64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
        env:
          npm_config_platform: linux
          npm_config_arch: ${{ matrix.arch }}
      - name: Install Sharp
        run: npm install --cpu=wasm32 sharp
      - name: Build
        run: npm run build

      - name: Check translations
        run: npm run i18n && npm run i18n:en
